title: Danilo Val
author:
  name: Danilo Val
  email: danilodoval@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  Desenvolvimento de software, tecnologia e afins.
show_excerpts: false # set to true to show excerpts on the homepage

newsletter: https://tinyletter.com/o_gabsferreira

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: dnlval
    github:  daniloval
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    instagram: dnlval
    linkedin: daniloval
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: G-ETDZVH7XPP        # Required - replace with your tracking id
    anonymizeIp: true       # Optional - Default: false - set to true for anonymized tracking

google_analytics: G-ETDZVH7XPP

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-analytics